update ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,7 +8,6 @@ on:
     branches: ["*"]
   merge_group:
 
-
 jobs:
   lint:
     runs-on: ubuntu-latest
@@ -42,6 +41,32 @@ jobs:
       - uses: ./.github/actions/setup
 
       - run: pnpm typecheck
+
+  check-changeset:
+    runs-on: ubuntu-latest
+    name: Check Changeset
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: ./.github/actions/setup
+
+      - name: Check and Validate Changes in tailwindcss-autocontrast
+        run: |
+          git fetch origin main:main
+          changes=$(git diff --name-only main...${{ github.sha }} | grep '^packages/tailwindcss-autocontrast/' || true)
+          if [[ -n "$changes" ]]; then
+            echo "Changes detected in tailwindcss-autocontrast: $changes"
+            pnpm changeset status --since origin/main
+            exit_status=$?
+            if [[ $exit_status -eq 0 ]]; then
+              echo "Changeset validation succeeded."
+            else
+              echo "Changeset validation failed."
+            fi
+          else
+            echo "No changes detected in tailwindcss-autocontrast"
+          fi
 
   test:
     runs-on: ubuntu-latest
